#!/bin/bash
set -o errexit
set -o nounset

export EMAIL="Jack Schwenderman <jack@qtr-horse.com>"
export use_from=YES

echo "Generated by Mutt in a Cron Job running on Render." | mutt -s "Render Test Cron" -- jack@qtr-horse.com
